### ISSUE TITLE
MongoDB log line from the decoder example is not matched

### ISSUE THREAD

**Issue by slavag** [wazuh/wazuh-ruleset#347] opened 2019-04-09 05:27 UTC
Hi,
I took a line from mongodb decoder (0405-mongodb_decoders.xml ) :
2017-03-27T19:32:31.916+0200 I ACCESS   [conn10000] Successfully authenticated as principal snapshots on myUser
Tried to test in ossec-logtest and got next :

2019/04/09 05:22:10 ossec-testrule: INFO: Started (pid: 4339).
ossec-testrule: Type one log per line.

2017-03-27T19:32:31.916+0200 I ACCESS   [conn10000] Successfully authenticated as principal snapshots on myUser

**Phase 1: Completed pre-decoding.
       full event: '2017-03-27T19:32:31.916+0200 I ACCESS   [conn10000] Successfully authenticated as principal snapshots on myUser'
       timestamp: '2017-03-27T19:32:31.916+0200 I '
       hostname: 'CCESS'
       program_name: '(null)'
       log: '  [conn10000] Successfully authenticated as principal snapshots on myUser'

**Phase 2: Completed decoding.
       No decoder matched.

Thanks

**Comment by Lopuiz** [comment] 2019-04-11 10:35
Hi @slavag,

You're right, pre-decoding doesn't work as expected for MongoDB. I've opened [issue](https://github.com/wazuh/wazuh/issues/3082) reporting bug.
Thank you for your feedback. We'll fix it in next releases.

Kind regards, Eva.

**Comment by slavag** [comment] 2019-04-11 15:54
Thanks !!!

**Comment by Lopuiz** [comment] 2019-04-22 08:08
Hi @slavag,
I'll close this issue because the problem is yet reported in wazuh's repository.  If you have another question you can open a new issue or reopen this one.
Kind regards, Eva

**Closed** 2019-04-22 08:08 UTC

**Comment by amitt00** [comment] 2022-09-08 07:49
Hello all,

The decoding problem is still there with mongo-db logs,2022
Though i tried few things and tweaking the inbuilt decoders and rules, can make it work.
Method-1
step-1: Write mongod logs in syslog then below decoder can decode mongodb logs, in wazuh
Decoder:
<decoder name="mongod_custom">
  <program_name>mongod</program_name>
</decoder>

<decoder name="mongod1">
  <parent>mongod_custom</parent>
  <prematch>^{\s*"</prematch>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
</decoder>

<decoder name="mongod2">
  <parent>mongod_custom</parent>
  <prematch>^[^\\{]+</prematch>
  <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
</decoder>

<decoder name="mongod3">
  <parent>mongod_custom</parent>
  <prematch>^(\\:)\s?</prematch>
  <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
</decoder>

####One of these will catch the fields,
Step:2
Copy the inbuilt mongodb ruleset(xml)  and change -
decoded as -> mongod_custom
"mongodb.severity" to "s"
"mongodb.component" to "c"

It works in my case.

##Method 2
Collect logs from /var/log/mongodb.log
Copy the inbuilt mongodb ruleset(xml)  and change -
decoded as -> json
"mongodb.severity" to "s"
"mongodb.component" to "c"

<Dont forget to change the rule numbering: in both methods>
<change what you want in description -> using $(attr.remote) etc

**Comment by amitt00** [comment] 2022-09-08 07:54
Hope it works : mongod log decoding and ruleset
