### ISSUE TITLE
Question about rules

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-ruleset#445] opened 2019-06-28 07:16 UTC
Hi,

I have tried a rule 80721 "User becomes root" ... And it didn't worked. I given root right at a user and I did : "sudo su" for past root and none event fordward to SIEM. So I tried to create a basic user and after in sudoers I given right root. And nothing in SIEM. What is this rule please ? How it works ?

**Comment by Zenidd** [comment] 2019-06-28 14:25
Hi @John33000,




I tried to trigger the`80721` rule without success. This rule triggers when an `ANOM_ROOT_TRANS` `auditd` event occurs.

After checking that rule `80721`  isn't triggered by giving root permissions to a user, i've looked on `auditd `logs (`/var/log/audit/audit.log`) to see if the problem is in `auditd` or in the way Wazuh processes the auditd logs. The event is missing also in auditd log.

After some searches seems like there are events that have a defined identifier but are not implemented. 

This is the case of `ANOM_ROOT_TRANS`. On this [thread](
https://www.mail-archive.com/linux-audit@redhat.com/msg09564.html) Steve Grubbs, from Redhat staff gives an user the further explanation about the `ANOM_ROOT_TRANS` event.

```
Not sure where this one is. But the main thing is that the ANOM and RESP 
classes of events are for use by IDS and IPS respectively. I have been slowly 
working my way back up the stack with the aim of providing and basic IDS/IPS 
plugin that will generate all these events. I think many of ANOM ones were in 
the prelude plugin and will be used again. For now they are placeholders.
```
As he points out, right now these events are placeholders and we can't use them to trigger rules.
<br></br>
If your target is monitoring when a user becomes root you can use `/var/log/secure`. Be sure that this log is included on (is so by default) `<!-- Log analysis -->` section on `ossec.conf`

```
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
```

You should be able to see alerts when an user becomes root, as those on the further example:
```
# adduser test_user
# usermod -aG wheel test_user
# su test_user
# sudo su

After these commands im able to see the further alerts:

** Alert 1561731735.225899: - syslog,sudo,pci_dss_10.2.5,pci_dss_10.2.2,gpg13_7.6,gpg13_7.8,gpg13_7.13,gdpr_IV_32.2,
2019 Jun 28 14:22:15 workerCentos->/var/log/secure
Rule: 5402 (level 3) -> 'Successful sudo to ROOT executed'
User: root
Jun 28 14:22:13 workerCentos sudo: test_user : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/su
tty: pts/0
pwd: /home/vagrant
command: /bin/su

** Alert 1561731735.226292: - pam,syslog,authentication_success,pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,
2019 Jun 28 14:22:15 workerCentos->/var/log/secure
Rule: 5501 (level 3) -> 'PAM: Login session opened.'
User: root
Jun 28 14:22:13 workerCentos sudo: pam_unix(sudo:session): session opened for user root by vagrant(uid=0)
uid: 0
```
Please let me know if it helps. We can look for other solutions so that you can visualize alerts of the events that you need.
<br></br>
Best regards,

Juan Pablo Sáez

**Comment by John33000** [comment] 2019-07-01 12:00
Hi Zenidd,

Thanks for you answer, indeed we saw when user becomes root with  
<localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>

But when I saw the rules "User becomes root" I thought to myself the payload is more explicit whereas  "/var/log/secure/"

Bests Regards

**Comment by Zenidd** [comment] 2019-07-02 14:50
Hi again @John33000,

> But when I saw the rules "User becomes root" I thought to myself the payload is more explicit whereas "/var/log/secure/"

I agree with you, the alert with the description "User becomes root" is more readable.

We are going to pay attention to the auditd updates so that when these events are implemented we take them into account for our ruleset.

Well @John33000, I'm closing this ticket, please don't hesitate to open another one if you have any questions or need our help.
<br></br>
Best regards,

Juan Pablo Sáez

**Closed by Zenidd** 2019-07-02 14:50 UTC
Labels: community, rules

**Comment by iabarca-s** [comment] 2021-04-26 17:08
Hi Zenidd.

I have RHEL8.3 kernel source  linux-4.18.0-240.el8.x86_64 and I'm trying to trigger those events:

1. - ANOM_ACCESS_FS
2. - ANOM_DEL_ACCT
3. - ANOM_LOGIN_ACCT
4. - ANOM_LOGIN_FAILURES
5. - ANOM_LOGIN_LOCATION
6. - ANOM_LOGIN_SESSIONS
7. - ANOM_MAX_DAC
8. - ANOM_MAX_MAC
9. - ANOM_MK_EXEC
10. - ANOM_MOD_ACCT
11. - ANOM_RBAC_FAIL
12. - ANOM_RBAC_INTEGRITY_FAIL
13. - ANOM_ROOT_TRANS

I found this information https://people.redhat.com/sgrubb/audit/audit-ids.pdf and get the audit logs in /var/log/audit/audit.log for 

1. ANOM_LOGIN_FAILURES
2. ANOM_LOGIN_LOCATION
3. ANOM_LOGIN_SESSIONS

I found this ticket and for this reason I would like to know if it is possible to trigger the other ANOM events or it isn't possible yet? 

Thanks,
Best regards,
Ivannia A
